# Generated by Django 6.0.1 on 2026-02-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelog',
            name='cost',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicelog',
            name='strategy',
            field=models.CharField(choices=[('ROUND_ROBIN', 'Round Robin'), ('NASH_EQ', 'Nash Equilibrium')], default='ROUND_ROBIN', max_length=20),
        ),
    ]
